--- !ruby/object:VR_ENV
backup_path: /home/eric
browser: firefox
builder: !ruby/object:Gtk::Builder {}
current_file: /home/eric/vrp/vrx/visualruby_examples/all_widgets/all_widgets.rb
font_name: Monospace 10
glade_path: glade-3
height: 600
open_files:
- /home/eric/vrp/vrx/visualruby_examples/all_widgets/bin/AllWidgets.rb
- /home/eric/vrp/vrx/visualruby_examples/all_widgets/all_widgets.rb
open_folders:
- /home/eric/vrp/vrx/visualruby_examples/all_widgets
- /home/eric/vrp/vrx/visualruby_examples/all_widgets/bin
- /home/eric/vrp/vrx/visualruby_examples/all_widgets/bin/glade
panel_pos: 360
rdoc_command_line: rdoc -x README
run_command_line: ruby all_widgets.rb
tab_spaces: 2
width: 800
