--- !ruby/object:VR_ENV
backup_path: /home/eric
browser: firefox
current_file: /home/eric/vrp/vrx/visualruby_examples/child_window/main.rb
font_name: Monospace 10
glade_path: glade-3
height: 600
open_files:
- /home/eric/vrp/vrx/visualruby_examples/child_window/bin/MyClass.rb
- /home/eric/vrp/vrx/visualruby_examples/child_window/bin/MyChildClass.rb
- /home/eric/vrp/vrx/visualruby_examples/child_window/main.rb
open_folders:
- /home/eric/vrp/vrx/visualruby_examples/child_window
- /home/eric/vrp/vrx/visualruby_examples/child_window/bin
panel_pos: 354
rdoc_command_line: rdoc -x README
run_command_line: ruby main.rb
tab_spaces: 2
width: 800
