--- !ruby/object:VR_ENV
browser: firefox
width: 934
height: 674
panel_pos: 453
backup_path: /home/eric
tab_spaces: 2
run_command_line: ruby active_record.rb
open_files:
- /home/eric/visualruby_examples/active_record/active_record.rb
- /home/eric/visualruby_examples/active_record/bin/ChoosePerson.rb
- /home/eric/vrp/vrx/visualruby_examples/active_record/bin/Person.rb
- /home/eric/vrp/vrx/visualruby_examples/active_record/bin/ChoosePerson.rb
- /home/eric/vrp/vrx/visualruby_examples/active_record/active_record.rb
open_folders:
- /home/eric/vrp/vrx/visualruby_examples/active_record
- /home/eric/vrp/vrx/visualruby_examples/active_record/db
current_file: /home/eric/vrp/vrx/visualruby_examples/active_record/active_record.rb
glade_path: glade-3
font_name: Monospace 10
rdoc_command_line: rdoc -x README
browser_box: !ruby/object:VR::SimpleComboBoxEntry {}
builder: !ruby/object:Gtk::Builder {}
glade_box: !ruby/object:VR::SimpleComboBoxEntry {}
