--- !ruby/object:VR_ENV
backup_path: /home/kb9agt
browser: firefox
builder: !ruby/object:Gtk::Builder {}
current_file: /home/kb9agt/Githubreposmine/GTK_Ruby/visualruby_examples/simple_ruby_gui/simple_ruby_gui
font_name: Monospace 10
glade_path: glade-3
height: 695
open_files:
- /home/kb9agt/Githubreposmine/GTK_Ruby/visualruby_examples/simple_ruby_gui/bin/DataObject.rb
- /home/kb9agt/Githubreposmine/GTK_Ruby/visualruby_examples/simple_ruby_gui/bin/DataObjectGUI.rb
- /home/kb9agt/Githubreposmine/GTK_Ruby/visualruby_examples/simple_ruby_gui/simple_ruby_gui
open_folders:
- /home/kb9agt/Githubreposmine/GTK_Ruby/visualruby_examples/simple_ruby_gui
- /home/kb9agt/Githubreposmine/GTK_Ruby/visualruby_examples/simple_ruby_gui/bin
- /home/kb9agt/Githubreposmine/GTK_Ruby/visualruby_examples/simple_ruby_gui/bin/glade
panel_pos: 360
rdoc_command_line: rdoc -x README
run_command_line: ruby simple_ruby_gui
tab_spaces: 2
width: 1024
glade_box: !ruby/object:VR::SimpleComboBoxEntry {}
browser_box: !ruby/object:VR::SimpleComboBoxEntry {}
