--- !ruby/object:VR_ENV
browser: firefox
width: 1070
height: 600
panel_pos: 360
backup_path: /home/eric
tab_spaces: 2
run_command_line: ruby main.rb
open_files:
- /home/eric/vrp/vrx/visualruby_examples/listview_objects/bin/ListViewObjectsGUI.rb
- /home/eric/vrp/vrx/visualruby_examples/listview_objects/bin/DataObject.rb
- /home/eric/vrp/vrx/visualruby_examples/listview_objects/bin/ListViewObjects.rb
- /home/eric/vrp/vrx/visualruby_examples/listview_objects/main.rb
open_folders:
- /home/eric/vrp/vrx/visualruby_examples/listview_objects
- /home/eric/vrp/vrx/visualruby_examples/listview_objects/bin
- /home/eric/vrp/vrx/visualruby_examples/listview_objects/bin/glade
current_file: /home/eric/vrp/vrx/visualruby_examples/listview_objects/bin/ListViewObjects.rb
glade_path: glade-3
font_name: Monospace 10
rdoc_command_line: rdoc -x README
