# source generated by foxGUIb 1.0.0

class MainWindow
	def initialize( parent)
		construct_widget_tree( parent)
		init if respond_to? 'init'
	end
	
	def construct_widget_tree( parent)
		@topwin=
		FX::MainWindow.new(parent){|w|
			@MainWindow=w
			#w.wdg_name='MainWindow'
			#w.backColor=Fox::FXRGBA(212,208,200,255)
			#w.width=216
			#w.hSpacing=0
			#w.shown=true
			#w.y=167
			#w.height=218
			#w.title="MainWindow"
			#w.vSpacing=0
			#w.x=262
			FX::VerticalFrame.new(@MainWindow){|w|
				@VerticalFrame=w
				#w.wdg_name='VerticalFrame'
				#w.baseColor=Fox::FXRGBA(212,208,200,255)
				#w.backColor=Fox::FXRGBA(212,208,200,255)
				#w.width=216
				#w.height=218
				#w.shadowColor=Fox::FXRGBA(139,137,132,255)
				FX::Button.new(@VerticalFrame){|w|
					@Button=w
					#w.wdg_name='Button'
					#w.baseColor=Fox::FXRGBA(212,208,200,255)
					#w.text="click to see what happens!"
					#w.backColor=Fox::FXRGBA(212,208,200,255)
					#w.font=FX::Font.new.from_s('Sans|90|0|0|0|0|0').to_FXFont
					#w.width=153
					#w.height=23
					#w.shadowColor=Fox::FXRGBA(139,137,132,255)
					@Button.connect(Fox::SEL_LEFTBUTTONRELEASE){
						@Text.appendText "button released\n"
						0 # this prevents fox from blocking the builtin event handler for leftbuttonpress
					}
					@Button.connect(Fox::SEL_LEFTBUTTONPRESS){
						@Text.appendText "button pressed\n"
						0 # this prevents fox from blocking the builtin event handler for leftbuttonpress
					}
					@Button.connect(Fox::SEL_COMMAND){
						@Text.appendText "button clicked\n"
					}
				}
				FX::Text.new(@VerticalFrame){|w|
					@Text=w
					#w.wdg_name='Text'
					#w.font=FX::Font.new.from_s('Sans|90|0|0|0|0|0').to_FXFont
					#w.width=216
					#w.selBackColor=Fox::FXRGBA(10,36,106,255)
					#w.y=23
					#w.height=195
				}
			}
		}
	end
	attr_reader :topwin
	attr_reader :MainWindow
	attr_reader :VerticalFrame
	attr_reader :Button
	attr_reader :Text
end

#unit test
if __FILE__==$0
	require 'libGUIb16'
	app=FX::App.new
	w=MainWindow.new app
	w.topwin.show(Fox::PLACEMENT_SCREEN)
	app.create
	app.run
end
