# source generated by foxGUIb 1.0.0

class MainWindow
	def initialize( parent)
		construct_widget_tree( parent)
		init if respond_to? 'init'
	end
	
	def construct_widget_tree( parent)
		@topwin=
		FX::MainWindow.new(parent){|w|
			@mainWindow=w
			w.wdg_name='mainWindow'
			w.width=532
			w.shown=true
			w.y=214
			w.height=536
			w.title="title= \"The Title\""
			w.x=76
			FX::Text.new(@mainWindow){|w|
				@text1=w
				w.wdg_name='text1'
				w.text="Hello World!"
				w.font=FX::Font.new.from_s('Arial Black|160|90|5|0|0|0').to_FXFont
				w.width=532
				w.height=536
			}
		}
	end
	attr_reader :topwin
	attr_reader :mainWindow
	attr_reader :text1
end

#unit test
if __FILE__==$0
	require 'libGUIb16'
	app=FX::App.new
	w=MainWindow.new app
	w.topwin.show(Fox::PLACEMENT_SCREEN)
	app.create
	app.run
end
