--- !ruby/object:VR_ENV
browser: firefox
width: 1346
height: 865
panel_pos: 541
backup_path: /home/eric
tab_spaces: 2
run_command_line: ruby active_record2.rb
open_files:
- /home/eric/vrp/vrx/visualruby_examples/active_record2/active_record2.rb
- /home/eric/vrp/vrx/visualruby_examples/active_record2/bin/CompanyGUI.rb
- /home/eric/vrp/vrx/visualruby_examples/active_record2/bin/Employee.rb
- /home/eric/vrp/vrx/visualruby_examples/active_record2/bin/Paycheck.rb
open_folders:
- /home/eric/vrp/vrx/visualruby_examples/active_record2
- /home/eric/vrp/vrx/visualruby_examples/active_record2/bin
current_file: /home/eric/vrp/vrx/visualruby_examples/active_record2/active_record2.rb
glade_path: glade-3
font_name: Monospace 10
rdoc_command_line: rdoc -x README
browser_box: !ruby/object:VR::SimpleComboBoxEntry {}
builder: !ruby/object:Gtk::Builder {}
glade_box: !ruby/object:VR::SimpleComboBoxEntry {}
