--- !ruby/object:VR_ENV
backup_path: /home/eric
browser: firefox
browser_box: !ruby/object:VR::SimpleComboBoxEntry {}
builder: !ruby/object:Gtk::Builder {}
current_file: /home/eric/vrp/vrx/visualruby_examples/calculator/main.rb
font_name: Monospace 10
glade_box: !ruby/object:VR::SimpleComboBoxEntry {}
glade_path: glade-3
height: 600
open_files:
- /home/eric/vrp/vrx/visualruby_examples/calculator/main.rb
open_folders:
- /home/eric/vrp/vrx/visualruby_examples/calculator
- /home/eric/vrp/vrx/visualruby_examples/calculator/bin
panel_pos: 360
rdoc_command_line: rdoc -x README
run_command_line: ruby main.rb
tab_spaces: 2
width: 800
