--- !ruby/object:VR_ENV
browser: C:\Program Files\iexplorer\iexplore.exe
width: 1190
height: 831
panel_pos: 525
backup_path: /home/eric
tab_spaces: 2
run_command_line: ruby main.rb
open_files:
- /home/eric/vrp/vrx/visualruby_examples/listview/bin/SongListView.rb
- /home/eric/vrp/vrx/visualruby_examples/listview/bin/SongListViewGUI.rb
open_folders:
- /home/eric/vrp/vrx/visualruby_examples/listview
- /home/eric/vrp/vrx/visualruby_examples/listview/bin
current_file: /home/eric/vrp/vrx/visualruby_examples/listview/bin/SongListView.rb
glade_path: glade-3
font_name: Monospace 10
rdoc_command_line: rdoc -x README
browser_box: !ruby/object:VR::SimpleComboBoxEntry {}
builder: !ruby/object:Gtk::Builder {}
glade_box: !ruby/object:VR::SimpleComboBoxEntry {}
